"""Fix Word model: compound uniqueness on (user_id, word)

Revision ID: 352e523c09d5
Revises: b4567890123de
Create Date: 2026-08-20 11:45:45.470523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '352e523c09d5'
down_revision = 'b4567890123de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('ix_topics_mode_id')

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_constraint('words_word_key', type_='unique')
        batch_op.create_unique_constraint('uq_word_user', ['user_id', 'word'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_constraint('uq_word_user', type_='unique')
        batch_op.create_unique_constraint('words_word_key', ['word'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index('ix_topics_mode_id', ['mode_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    # ### end Alembic commands ###
